stages:
  data:
    cmd: python src/get_data.py
    deps:
    - src/get_data.py
    outs:
    - data/creditcard.csv
  Preprocessing:
    cmd: python src/preprocessing_data.py
    deps:
    - src/preprocessing_data.py
    - data/creditcard.csv
    outs:
    - data/data_preprocessed.csv
  Train:
    cmd: python src/train.py
    deps:
    - src/train.py
    - data/data_preprocessed.csv
    outs:
    - model.pkl
    metrics:
    - metrics.json:
        cache: false