name: Machine Learning Automate Python application
on: [push]
jobs:
  run:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Running_updates
        env: 
          GH_TOKEN: ${{ github.token }}
        run: |
          make install
     - name: Pull data from DVC
        run: |
          dvc remote modify origin --local auth basic
          dvc remote modify origin --local user ${{ secrets.GDRIVE_ID }}
          dvc remote modify origin --local password ${{ secrets.GDRIVE_SECRET }}
          dvc pull
      
      - name: Run the pipeline with DVC
          dvc repro
          git fetch --prune
          dvc metrics diff --show-md main > report.md
          gh pr comment ${{github.event.pull_request.number}} -F report.md
